### ISSUE TITLE
希望可以支持设置proxy

### ISSUE THREAD

**Issue by dan-kuroto** [Xinrea/JPet#9]
如题。公司WiFi把B站ban了，不挂代理上不去。

如果方便的话希望能支持一下

~~要是不好做的话就算了~~

**Comment by Xinrea** [comment]
就算这样也要挂着吗（，这个需求可能太小众了，应该不会做；而且我记得应该有通用的解决方案来着，例如这个 [proxifier](https://www.proxifier.com)，可以指定部分进程走 proxy，还可以解决其他类似软件同样的代理问题。
